# ╭──────────────────────────────────────ImplementationGuide───────────────────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. For a list of       │
# │  supported properties, see: https://fshschool.org/docs/sushi/configuration/                    │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: kl.dk.fhir.rehab
canonical: http://fhir.kl.dk/rehab
name: KLGatewayRehab
description: Danish municipalities implementation guide for §140 rehabilitation reporting
status: active
version: 2.2.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: Release #ci-build
publisher:
  name: Kommunernes Landsforening
  url: http://kl.dk

dependencies:
  hl7.fhir.dk.core: 3.2.0
  kl.dk.fhir.term: 2.2.0
  
# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To use a provided input/includes/menu.xml file, delete the "menu" property below.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
  Home: index.html
  Artifacts: artifacts.html
  Example: example.html

